// MGetKV3ClassDefaults = Could not parse KV3 Defaults
// MVDataOutlinerAssetNameExpr (UNKNOWN FOR PARSER)
class CSmartPropElement_ModelEntity : public CSmartPropElement
{
	// MPropertyDescription = "Name of the model resource (.vmdl) to place."
	// MPropertyProvidesEditContextString = "ToolEditContext_ID_VMDL"
	CSmartPropAttributeModelName m_sModelName;
	// MPropertyFriendlyName = "Material Group"
	// MPropertyDescription = "Specifies the name of the material group (skin) to use when displaying the specified model."
	CSmartPropAttributeMaterialGroup m_MaterialGroupName;
	// MPropertyFriendlyName = "Cast Shadows"
	// MPropertyDescription = "Should the entity created by this element cast shadows."
	CSmartPropAttributeBool m_bCastShadows;
	// MPropertyFriendlyName = "Force Static"
	// MPropertyDescription = "Force this model to be placed as a static model rather then generating an entity."
	CSmartPropAttributeBool m_bForceStatic;
	// MPropertySortPriority = -1
	// MPropertySuppressExpr = "m_bForceStatic == true"
	// MPropertyFriendlyName = "Attachment Mode"
	// MPropertyGroupName = "Deformable Entity Settings"
	// MPropertyDescription = "If the smart prop is child of a deformable entity, this setting specifies how the entity generated by this element will be attached to the deformable surface."
	SmartPropDeformableAttachMode_t m_nDeformableAttachmentMode;
	// MPropertySortPriority = -1
	// MPropertySuppressExpr = "m_bForceStatic == true"
	// MPropertyGroupName = "Deformable Entity Settings"
	// MPropertyDescription = "If the smart prop is child of a deformable entity, this setting specifies how the entity generated by this element will be oriented relative to the deformable surface."
	SmartPropDeformableOrientMode_t m_nDeformableOrientationMode;
};
